name: Workflow  

on: 
  workflow_dispatch:
  
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 18
      
      - name: Install Dependencies
        run: npm ci --silent

      - name: Build
        run: npm run build -w frontent

      - name: Archive Production Artifact
        uses: actions/upload-artifact@master
        with:
          name: front
          path: frontend/dist
