name: My first workflow

on:
  workflow_dispatch:
  
  push:
    branches:
    - master
    
jobs:
  compile: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3
    

  
  
