name: My first workflow

on:
  workflow_dispatch:
  
  push:
    branches:
    - master
    
jobs:
  compile: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3
        
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.6.0
        with:
          node-version: 18.16.0
        
      - name: Install
        run: npm ci --silent
        
      - name: Build
        run: npm run build -w frontend

      - name: Archive Production Artifact
        uses: actions/upload-artifact@master
        with:
          name: frontend
          path: frontend/dist
          

 
          
        

    

  
  
